Management/urls.py
from django.urls import path
from . import views


app_name = "Management"
urlpatterns=[
    path("", views.index, name="Home"),
    path("fav/", views.view_fav, name="View_Favourite"),
    path("addfav/", views.add_fav, name="Add_Favourite"),
    path("addcompl/", views.add_complaint, name="Add_Complaint"),
    path("compl/", views.view_complaint, name="View_Complaint"),
    path("search/", views.search, name="Search"),
    path("signup/", views.sign_up, name="Sign_Up")
]

Payroll_Management_System/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Payroll/', include("Management.urls"))
]

Management/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    Name = models.CharField(max_length=64)
    Email = models.CharField(max_length=64)
    Password = models.CharField(max_length=64)
    Position = models.CharField(max_length=64)
    Salary = models.IntegerField()


    def __str__(self):
        return f"{self.id}: {self.Name} is {self.Position} with salary of {self.Salary}. Email:{self.Email} and Password:{self.Password}"

Management/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.urls import reverse
from .models import Employee

#Adding Favorite List
favorites = []

#Adding Complaint List
complaint_author = []
complaint_email = []
complaint_type = []
complaint_subject = []
complaint_message = []

class NewFavForm(forms.Form):
    new_favorite = forms.CharField(label="New Favorite", required="True")

class NewComplaintForm(forms.Form):
    name = forms.CharField(label="Your name:", max_length=100, required="True")
    sender = forms.EmailField(label="Your Email:", required="True")
    c_type = forms.CharField(label="Complaint Type:", required="True")
    subject = forms.CharField(label="Subject:", min_length=10, required="True")
    message = forms.CharField(label="Message:", max_length=300, required="True")

class NewSearchForm(forms.Form):
    query = forms.CharField(label="Employee Name:", max_length=100, required="True")

class NewSignupForm(forms.Form):
    Name = forms.CharField(label="Your Name:",max_length=64)
    Email = forms.EmailField(label="Your Email:",max_length=64)
    Password = forms.CharField(label="Password",max_length=64)
    Position = forms.CharField(label="Your Position",max_length=64)
    Salary = forms.IntegerField(label="Your Salary:")


# Create your views here.
def index(request):
    return render(request, "Management/index.html", {
        "favorites": favorites
    })

def view_fav(request):
    return render(request, "Management/favourite.html", {
        "favorites": favorites
    })

def add_fav(request):
    if request.method == "POST":
        form = NewFavForm(request.POST)
        if form.is_valid():
            new_favorite = form.cleaned_data["new_favorite"]
            favorites.append(new_favorite)
            return HttpResponseRedirect(reverse("Management:Add_Favourite"))
        else:
            return render(request, "Management/add_favourite.html", {
                "form": form,
                "favorites": favorites
            })
    
    return render(request, "Management/add_favourite.html", {
        "form": NewFavForm(),
        "favorites": favorites
    })

def add_complaint(request):
    if request.method == "POST":
        form = NewComplaintForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            sender=form.cleaned_data["sender"]
            c_type=form.cleaned_data["c_type"]
            subject=form.cleaned_data["subject"]
            message=form.cleaned_data["message"]
            complaint_author.append(name)
            complaint_email.append(sender)
            complaint_type.append(c_type)
            complaint_subject.append(subject)
            complaint_message.append(message)
            return HttpResponseRedirect(reverse("Management:Add_Complaint"))
        else:
            return render(request, "Management/add_complaint.html", {
                "form": form,
                "favorites": favorites
            })
    
    return render(request, "Management/add_complaint.html", {
        "form": NewComplaintForm(),
        "favorites": favorites
    })

def view_complaint(request):
    return render(request, "Management/complaint.html", {
        "Complaint": zip(complaint_author, complaint_email, complaint_type, complaint_subject, complaint_message),
        "favorites": favorites
    })

def search(request):
    result = "NONE"
    if request.method == "POST":
        form = NewSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            result = Employee.objects.filter(Name=query)
            return render(request, "Management/search.html", {
                "form": form,
                "result": result,
                "method": request.method,
                "favorites": favorites
            })
        else:
            return render(request, "Management/search.html", {
                "result": result,
                "form": form,
                "method": request.method,
                "favorites": favorites
            })
    
    return render(request, "Management/search.html", {
        "result": result,
        "form": NewSearchForm(),
        "method": request.method,
        "favorites": favorites
    })

def sign_up(request):
    if request.method == "POST":
        form = NewSignupForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["Name"]
            email = form.cleaned_data["Email"]
            password = form.cleaned_data["Password"]
            position = form.cleaned_data["Position"]
            salary = form.cleaned_data["Salary"]
            new_employee = Employee(Name= name, Email= email, Password= password, Position= position, Salary= salary)
            new_employee.save()
            return HttpResponseRedirect(reverse("Management:Sign_Up"))
        else:
            return render(request, "Management/signup.html", {
                "form": form,
                "favorites": favorites
            })
    
    return render(request, "Management/signup.html", {
        "form": NewSignupForm(),
        "favorites": favorites
    })

Management/templates/Management/add_complaint.html
{% extends "Management/layout.html" %}

{% block title %} New Complaint {% endblock title %}



{% block body %}
<h1>Add a new Complaint</h1>
<form action="{% url 'Management:Add_Complaint' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</div>
<div class="repoContainer">
    <a href="{% url 'Management:View_Complaint' %}">View all complaints</a>
{% endblock body%}

Management/templates/Management/add_favourite.html
{% extends "Management/layout.html" %}

{% block title %} Add Favourites {% endblock title %}

{% block body %}
    <h1>Add Favorites</h1>
    <form action="{% url 'Management:Add_Favourite' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <div class="container">
        <a href="{% url 'Management:View_Favourite' %}">View Tasks</a>
    </div>
{% endblock %}

Management/templates/Management/complaint.html
{% extends "Management/layout.html" %}

{% block title %} Complaints {% endblock title %}



{% block body %}
<h1>All Complaints</h1>
</div>
<div class="repoContainer" style="overflow-y: hidden;">
    <table id="code" style="position: relative; margin-right: 30px; padding: 15px;border-spacing:30px;">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Complaint Type</th>
            <th>Complaint Subject</th>
            <th>Complaint Message</th>
        </tr>
        {% for Comp in Complaint %}
        <tr>
            <td>{{Comp.0}}</td>
            <td>{{Comp.1}}</td>
            <td>{{Comp.2}}</td>
            <td>{{Comp.3}}</td>
            <td>{{Comp.4}}</td>
        </tr>
        {% empty %}
            <td colspan="5" style="text-align: center; color: aqua;">No Complaint</td>
        {% endfor %}
    </table>
{% endblock body%}
{% block sec_body %}
    <a href="{% url 'Management:Add_Complaint' %}" style="position: relative;">Add a New Complaint</a>
{% endblock sec_body %}

Management/templates/Management/favourite.html
{% extends "Management/layout.html" %}

{% block title %} View Favourite {% endblock title %}

{% block body %}
<h1>Favorites</h1>
<div class="skills">
    <ul>
        {% for fav in favorites %}
            <span>{{ fav }}</span>
            {% empty %}
            <p>No Such Favorites</p>
        {% endfor %}
    </ul>
</div>
    <a href="{% url 'Management:Add_Favourite' %}">Add a New Favourite</a>
{% endblock body %}

Management/templates/Management/index.html
{% extends "Management/layout.html" %}

{% block title %} Home Page {% endblock title %}



{% block body %}
<h1>Features:</h1>
<a href="/admin/" class="repoCard" target="_blank" rel="noopener noreferrer">
   <div class="repoTitle">Login</div>
   <p>Login for Admins</p>
   <div><span>Login</span><span>Admin</span></div>
</a>
<a href="{% url 'Management:Sign_Up' %}" class="repoCard" rel="noopener noreferrer">
    <div class="repoTitle">Signup for Employee</div>
    <p>Employee Register Here!!</p>
    <div><span>Login</span><span>Employee</span></div>
</a>
<a href="{% url 'Management:Add_Complaint' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Report a complaint</div>
   <p>Bug Reports, Complaint Filing System</p>
   <div><span>Form</span><span>Bugs</span></div>
</a>
<a href="{% url 'Management:Add_Favourite' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Add A New Favorite</div>
   <p>Adding a new favorite</p>
   <div><span>Favorite</span><span>Add</span></div>
</a>
<a href="{% url 'Management:Search' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Search an Employee</div>
   <p>Seach Emplyee With there names</p>
   <div><span>Search</span><span>Employee</span></div>
</a>
{% endblock body%}

Management/templates/Management/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <link rel="shortcut icon" type="image/ico" href="{% static 'Management/favicon.ico' %}"/>
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
      <title>
        {% block title %}
        {{ page_title|default:"Payroll Management System" }}
        {% endblock title %}
    </title>
      <link href="{% static 'Management/styles.css' %}" rel="stylesheet">
   </head>
   <body>
      <div id="root">
         <div class="container">
            <div class="sidebar user">
               <div>
                  <a href="{% url 'Management:Home' %}">
                     <div class="avatar shine">
                        <img src="https://res.cloudinary.com/garvitjoshi9/image/upload/v1594407409/Git-Hub/1_4_ebmyhb.jpg" class="profile" alt="Company Picture">
                     </div>
                  </a>
                  <h1>Payroll Management System</h1>
                  <p>A Reliable Management System made for the Elites.</p>
               </div>
               <div>
                  <h3>Favorites:</h3>
                  <div class="skills">
                     {% for fav in favorites %}
                     <span>{{ fav }}</span>
                     {% empty %}
                     <p>No Such Favorites</p>
                     {% endfor %}
                  </div>
               </div>
               <div class="details">
                  <h3>About Developer:</h3>
                  <div><i class="fab fa-github-alt"></i><a href="https://github.com/garvit-joshi" target="_blank" rel="noopener noreferrer" style="color: inherit;">@garvit-joshi</a></div>
                  <div><i class="fas fa-building"></i><a href="https://www.lpu.in/" target="_blank" rel="noopener noreferrer" style="color: inherit;">Lovely Professional University</a></div>
                  <div><i class="fas fa-map-marker-alt"></i><a href="https://www.google.com/search?q=Phagwara+Punjab" target="_blank" rel="noopener noreferrer" style="color: inherit;">Phagwara, Punjab</a></div>
               </div>
            </div>
            <div class="main">
               <div class="repoContainer">
                  {% block body %}
                  {% endblock body %}
               </div>
               <div class="repoContainer">
                  {% block sec_body %}
                  {% endblock sec_body %}
               </div>
            </div>
         </div>
      </div>
   </body>
</html>

Management/templates/Management/search.html
{% extends "Management/layout.html" %}

{% block title %} Search {% endblock title %}



{% block body %}
{% if method == "GET" %}
    <h1>Search an Employee</h1>
{% else %}
    <h1>Results</h1>
{% endif %}
<form action="{% url 'Management:Search' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</div>
<div class="repoContainer">
    {% if not result and method == "POST" %}
        <p>No Result Found</p>
    {% elif method == "GET" %}
        <p></p>
    {% else %}
        <table id="code" style="position: relative; margin-right: 30px; padding: 15px;border-spacing:30px;">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Position</th>
            </tr>
            {% for r in result %}
                <tr>
                    <td>{{ r.id }}</td>
                    <td>{{ r.Name }}</td>
                    <td>{{ r.Email }}</td>
                    <td>{{ r.Position }}</td>
                </tr>
            {% empty %}
                <td colspan="5" style="text-align: center; color: aqua;">No Result</td>
            {% endfor %}
        </table>
    {% endif %}
{% endblock body%}

Management/templates/Management/signup.html
{% extends "Management/layout.html" %}

{% block title %} SignUp {% endblock title %}

{% block body %}
    <h1>Signup</h1>
    <form action="{% url 'Management:Sign_Up' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <div class="container">
        <a href="{% url 'Management:Home' %}">Home</a>
    </div>
{% endblock %}